version: "3"

services:
  # fwaze_ui:
  #   build: ./fwaze-ui
  #   container_name: fwaze-ui
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./fwaze-ui/:/app
  #   depends_on:
  #     - users_service
  #     - reports_service
  #     - ads_service
  #     - push_service
  #   links:
  #     - users_service
  #     - reports_service
  #     - ads_service
  #     - push_service

  # fwaze_node:
  #   build: ./fwaze
  #   container_name: fwaze_api
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./fwaze/:/usr/src/app
  #   depends_on:
  #     - fwaze_db_server
  #     - redis_server
  #     - kafka
  #   links:
  #     - fwaze_db_server
  #     - redis_server
  #     - kafka
  #   environment:
  #     - DB_HOST=fwaze_db_server
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=root
  #     - DB_NAME=fwaze_db
  #     - REDIS_URL=redis://redis_server
  #     - KAFKA_HOST_NAME=kafka
  #     - KAFKA_PORT=9092
  #   command: "bash start.sh fwaze_db_server:3306"

  reports_service:
    build: ./reports_ms
    container_name: reports_ms
    ports:
      - 3001:3001
    volumes:
      - ./reports_ms/:/usr/src/app
    depends_on:
      - fwaze_db_server
      - redis_server
      - kafka
    links:
      - fwaze_db_server
      - redis_server
      - kafka
    environment:
      - PORT=3001
      - DB_HOST=fwaze_db_server
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=reports_service_db
      - REDIS_URL=redis://redis_server
      - KAFKA_HOST_NAME=kafka
      - KAFKA_PORT=9092
    command: "bash start.test.sh fwaze_db_server:3306"

  users_service:
    build: ./users_ms
    container_name: users_ms
    ports:
      - 3002:3002
    volumes:
      - ./users_ms/:/usr/src/app
    depends_on:
      - fwaze_db_server
      - redis_server
      - kafka
    links:
      - fwaze_db_server
      - redis_server
      - kafka
    environment:
      - PORT=3002
      - DB_HOST=fwaze_db_server
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=users_service_db
      - REDIS_URL=redis://redis_server
      - KAFKA_HOST_NAME=kafka
      - KAFKA_PORT=9092
    command: "bash start.test.sh fwaze_db_server:3306"

  ads_service:
    build: ./ads_ms
    container_name: ads_ms
    ports:
      - 3003:3003
    volumes:
      - ./ads_ms/:/usr/src/app
    depends_on:
      - fwaze_db_server
      - redis_server
      - kafka
      - users_service
    links:
      - fwaze_db_server
      - redis_server
      - kafka
      - users_service
    environment:
      - PORT=3003
      - DB_HOST=fwaze_db_server
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ads_service_db
      - REDIS_URL=redis://redis_server
      - KAFKA_HOST_NAME=kafka
      - KAFKA_PORT=9092
    command: "bash start.test.sh fwaze_db_server:3306"

  push_service:
    build: ./push_ms
    container_name: push_ms
    ports:
      - 3004:3004
    volumes:
      - ./push_ms/:/usr/src/app
    depends_on:
      - redis_server
      - kafka
    links:
      - redis_server
      - kafka
    environment:
      - PORT=3004
      - REDIS_URL=redis://redis_server
      - KAFKA_HOST_NAME=kafka
      - KAFKA_PORT=9092

  fwaze_db_server:
    image: mysql:5.7.27
    container_name: fwaze_mysql
    ports:
      - "3308:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=Etc/UTC

  redis_server:
    image: redis
    container_name: redis_server
    ports:
      - "6380:6380"
    command: "redis-server"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: "reports_ms_commands:20:1\n\
        reports_ms_events:20:1\n\
        users_ms_commands:20:1\n\
        users_ms_events:20:1\n\
        ads_ms_commands:20:1\n\
        ads_ms_events:20:1\n\
        push_ms_events:20:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
